### ISSUE TITLE
Batch transcription speaker diarization not working (at all)

### ISSUE THREAD

**Issue by h4rr0d** [Azure-Samples/cognitive-services-speech-sdk#1051]
**Overview of the Issue**
Speaker diarization feature of Batch Transcription is not working for me at all (trying on eastus). I've tried several files and thought that maybe it had trouble because the voices sounded similar, but it doesn't seem to work even in a sample with female and male speakers. It seems, that the _DiarizationEnabled_ property is simply being ignored, because the resulting transcription JSON doesn't have the _Speaker_ property at all.

**Version**
API client generated in Visual Studio 2019 from the latest swagger documentation (https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0)

**Motivation for or Use Case**
Using the batch transcription API for transcribing audio samples of a two person conversation with speaker separation.

**Reproduce the Error**
Create a batch transcription task of the file I've attached [Conversation Test.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6352527/Conversation.Test.zip)
with the following settings
```c#
new Transcription
{
    ContentUrls = new List<string> {"url_to_file"},
    Properties = new TranscriptionProperties {
        DiarizationEnabled = true, 
        WordLevelTimestampsEnabled = true
    },
    Locale = "en-US",
    DisplayName = "Conversation Test"
};
```
File is transcribed successfully, but the _Speaker_ property is completely missing from the resulting JSON.

**Related Issues**
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/301

**Suggest a Fix**
Ideally fix the diarization, but if the diarization fails for whatever reason, there should at least be a notification about that in the transcription report or anywhere else.

**Comment by chlandsi** [comment]
Please post the transcription id and the approximate time of your request so we can correlate with service logs. Thanks!

**Comment by h4rr0d** [comment]
```
id: 993cac41-84fc-427c-b8bd-b5ff3a31e7fd
"createdDateTime": "2021-04-21T16:35:58Z"
```

**Comment by chlandsi** [comment]
I noticed that your file is in stereo. For stereo files, diarization is not possible, and the diarization flag is silenty ignored, which clearly is a bug. A fix for the issue is already underway and will be deployed in the next few days - it will not perform any processing and give a clear error message in this case. Until then, a workaround is to downmix all files to mono if diarization is requested. We are sorry for the inconvenience.

**Comment by h4rr0d** [comment]
I completely missed that last sentence in the documentation. Sorry about that.

**Comment by h4rr0d** [comment]
After downsampling the audio to mono and running it through the transcriber, the speaker separation seems to be fairly random and very incorrect, often putting both the speakers into one phrase (which is strange, considering it's male and female voice). Is there a way to increase the accuracy of the recognition? I also tried another sample without background music, but the diarization wasn't much better.

**Comment by chlandsi** [comment]
We'll be rolling out changes to the diarization service over the next few weeks, please stay tuned.

**Comment by kleindev** [comment]
@chlandsi just curious if anything changed on batch / diarization recently?  I am seeing an content that I was previously able to workaround by enabling diarization no longer being a viable workaround.  For example, 

![image](https://user-images.githubusercontent.com/9289866/117715176-8e480b00-b19d-11eb-8139-9e70e1c0cbdb.png)


For reference on history:  

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/892#issuecomment-740751808

**Comment by chlandsi** [comment]
Hi @kleindev, there was indeed a change that temporarily broke custom pronunciation. We have rolled back that change in South Central US. Please let us know if you are using that feature in other regions. We are sorry for the inconvenience.

**Comment by kleindev** [comment]
We are only using in South Central.  Happy to test out changes if needed as well

**Comment by jhakulin** [comment]
@kleindev @chlandsi Based on the previous comments, the issue is known and resolved in South Central US. Let us know if there is still any problems.

**Comment by HMZijlstra** [comment]
Hi, I am using this API in the Netherlands and it seems that this problem is not yet resolved if I want to use it for  Dutch audiofiles.

If I want to use the API with a stereo file and speaker diarization it does not work. However, when I disable the diarization it does work. 

This is the time, id and  place: 04:50:47 PM West-Europa (summertime) Created new transcription with id 'c61a48da-e43e-47d9-bd3e-ad4a75a0fbf8' in region northeurope

**Comment by zhouwangzw** [comment]
The speaker diarization feature only works for mono audio, but not for stereo audio, as described here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription#configuration-properties. 
There was a bug in the previous system which ignores the diarization setting but just does transcription for stereo files. This bug has been fixed in most regions and will be deployed to all regions soon.

**Comment by jhakulin** [comment]
closing the issue as the fix is being deployed, let us know if there is still issues.

**Comment by kleindev** [comment]
@jhakulin was this reintroduced into South Central US just recently?  We are now seeing the same issue appear for custom pronunciations - this was transcribed yesterday (5/27/2021)

subacromial**fdfdaabcaeaedcbabf** decompression

**Comment by zhouwangzw** [comment]
Sorry, a new deployment overwrote the setting by accident. I will revert the change.

**Comment by kleindev** [comment]
@zhouwangzw thank you!

**Comment by zhouwangzw** [comment]
I reverted the change, and the custom prounciations should work now. Sorry for the mistake!

**Comment by rseghier** [comment]
Same here: Speaker diarization feature of Batch Transcription is not working
It only shows one speaker: "speaker: 1"
Not a single line is attributed to "speaker: 2"
I made sure my audio files are mono. 
I tried with or without wordLevelTimestampsEnabled.

id '3ea88f70-aaaa-4bd9-99a9-93d23f17b462' in region eastus

**Comment by zhouwangzw** [comment]
@rseghier It seems your issue is different. You did get diarization result, but you think that the diarization result is not correct (only Speaker 1), so it is an accuracy issue. Would it be possible to share the audio? If you do not want to share audio here, you can open an Azure support ticket and we will investigate. Thanks!

**Comment by rseghier** [comment]
@zhouwangzw thanks, here is the audio file:  
https://transcripttests.blob.core.windows.net/testfiles/pulpfiction.mp3

**Comment by zhouwangzw** [comment]
@rseghier  I can repro the issue on our side. I will ask our scientist team to take a closer look why only 1 speaker is recognized. Sorry for the inconvenience!

**Comment by rseghier** [comment]
@zhouwangzw sure! In the meanwhile is there any alternative solution to could allow me to test this diarization feature?

**Comment by zhouwangzw** [comment]
Diarization should work in general. The accuracy error is usually related to specific audios. If you failures or incorrect speakers recognized, please let us know, and we will investigate. Thanks!

**Comment by rseghier** [comment]
@zhouwangzw would you be able to provide me with a file for which diarization works so that I can test it  on my side?

**Comment by zhouwangzw** [comment]
We have some test audios we used for internal testing, but unfortunately we cannot share them externally due to potential copyright issues.

**Comment by rseghier** [comment]
@zhouwangzw your own sample file katiesteve.wav does not work either it seems https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/cpp/windows/console/samples

**Comment by zhouwangzw** [comment]
The file you referred to (Katiesteve.wav) is a 8-channel wav file, which is used as sample for Conversation Transcriber, so this cannot be used for batch transcription. Batch transcription only supports diarization for mono file.

 Input File     : 'samples\cpp\windows\console\samples\katiesteve.wav'
**Channels       : 8**
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:19.18 = 306898 samples ~ 1438.58 CDDA sectors
File Size      : 4.91M
Bit Rate       : 2.05M
Sample Encoding: 16-bit Signed Integer PCM

**Comment by zhouwangzw** [comment]
@rseghier We did investigation, and it was due to issue in the diarization model that is currently being used. We have provided feedback to our science team and they are working on improvement to provide better accuracy in the upcoming release of the model. Unfortunately at this moment we do not have ETA for the new release yet. 

Thanks for your feedback and sorry for the inconvenience!

**Comment by aparnaji** [comment]
Pls let know if any new model is published, I am having similar issue, the recognition of speaker 1 and speaker 2 separation is very minimal, most of  it gets attributed to first speaker 1 and very minimal on speaker 2. I cannot share my files here

**Comment by linaelf** [comment]
> Pls let know if any new model is published, I am having similar issue, the recognition of speaker 1 and speaker 2 separation is very minimal, most of it gets attributed to first speaker 1 and very minimal on speaker 2. I cannot share my files here

@aparnaji We are working on improving the diarization right now, hopefully to release new version in a few weeks. Will keep you posted. Thanks!

**Comment by suppenburger** [comment]
> > Pls let know if any new model is published, I am having similar issue, the recognition of speaker 1 and speaker 2 separation is very minimal, most of it gets attributed to first speaker 1 and very minimal on speaker 2. I cannot share my files here
> 
> @aparnaji We are working on improving the diarization right now, hopefully to release new version in a few weeks. Will keep you posted. Thanks!

@aparnaji & @chlandsi & @zhouwangzw still diarization works with 2 speakers only, any info when the number will be increased?

**Comment by zhouwangzw** [comment]
@linaelf Could you please take a look at this issue?

**Comment by suppenburger** [comment]
@zhouwangzw @linaelf any update on this?

**Comment by kamrapooja** [comment]
Hi we are creating application in python for speech to text and we are using azure cognitive services for the same.
import azure.cognitiveservices.speech
speech_config = speechsdk.SpeechConfig(subscription=key, endpoint=endpoint)
speech_config.request_word_level_timestamps()
speech_config.diarizationEnabled(True)
speech_config.output_format=speechsdk.OutputFormat.Simple
speechsdk.audio.AudioConfig(filename=audio_file)
audio_config = speechsdk.audio.AudioConfig(filename=audio_file)
try:
  speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
  speech_recognizer.recognized.connect(add_to_res)
  speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
  speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
  speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
  speech_recognizer.session_stopped.connect(stop_cb)
  speech_recognizer.canceled.connect(cancel_cb)
  speech_recognizer.start_continuous_recognition()
    
Here we are setting output format as Simple. Also we need to set property to enable diarization. But not able to understand how to enable it. Please help

**Comment by zhouwangzw** [comment]
@kamrapooja The code you are using is not for Batch transcription, but for realtime transcription. If this is what you intend for, please look at Speech SDK documentation for details: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=android%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio. The python API reference is https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech?view=azure-python. 

If you have new questions, please open a new issue, instead of using a closed one, for better tracking. 

Thanks!

**Comment by kamrapooja** [comment]
Thanks a lot.
One doubt, batch Transcription can be used with blob storage only or it can be used on local stored files as well?
Please respond

**Comment by zhouwangzw** [comment]
batch transcription works with blob storage, and other http downloadable sources. If you store files locally, you need to have a HTTP server to make these files be accessible.

**Comment by ajeet95charan** [comment]
@zhouwangzw we have been trying to use batch transcription to detect whether the audio has more than one speaker but diarization is not working. every time it is giving speaker 1 only

we are running speech service in south central US also set diarization enabled with wordLevelTimestampsEnabled

not getting a single line for speaker 2 

please respond

**Comment by vinodk-ms** [comment]
Hello, was batch diarization issue resolved for Australia East. I tried with multiple wav and m4a files and transcription works without diarization but if I enable diarization then it gives error : Transcription failed: The recordings URI contains invalid data.

**Comment by zhouwangzw** [comment]
@vinodk-ms is your audio stereo or mono? For stereo files, diarization is not possible, and will return error in the response. Could you please check the error message in the transcription report file which should provide more detailed information than in the response? If you still have problem, please open a new issue and share your transcription id, and we will check.

**Comment by vinodk-ms** [comment]
hello @zhouwangzw , thanks for the reply, I did not receive any error message: Below are my transaction id:

11/18/2024 02:18:30 PM AEDT Starting transcription client...
11/18/2024 02:18:30 PM AEDT Created new transcription with id '764ca65b-f383-4ace-a31a-68d81568afc1' in region australiaeast
11/18/2024 02:18:30 PM AEDT Checking status.

**Comment by zhouwangzw** [comment]
@vinodk-ms For this transcription d702c675-eaf3-4fd2-a2d3-aed2c6ee5f77, I see that we do provide speaker information in the transcription result. There is a "speaker" property for each phase list under recognizedPhases in the transcription result file.

"recognizedPhrases": [
    {
      "recognitionStatus": "Success",
      "channel": 0,
      "speaker": 1,

**Comment by CHELLAA** [comment]
"contentUrls": [audio_file_path],
        "locale": "en-US",
        "displayName": "My Transcription",
        "model": None,
        "properties": {
            "diarizationEnabled": True,
            "wordLevelTimestampsEnabled": True,
            "languageIdentification": {
            "candidateLocales": [
                "en-US", "de-DE", "es-ES"
            ],
            "mode": "Continuous"
            },
            "timeToLiveHours": 48
        }

if i use diarizationEnabled = True means it is not working showing error like   "error": "The recordings URI contains invalid data." 

without diarizationEnabled it is working but with "unknown" as speaker name
