### ISSUE TITLE
SDK 1.19 'MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h' file not found build on build on Any iOS Device(arm 64)

### ISSUE THREAD

**Issue by FanChen2016** [Azure-Samples/cognitive-services-speech-sdk#1320]
build on Any iOS Device(arm 64),
Showing All Messages
xxx/one-app/NativePluginProjects/iOS/NativeAudioPlugin/AudioPlugin/AudioPlugin/AudioRecorder.h:7:9: 'MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h' file not found
build on simulator is OK

**Comment by jhakulin** [comment]
@FanChen2016 Thanks for the report, we will investigate. In 1.19.0 we have changed to xcframework. Are you using existing project with Speech SDK and when you moved to the latest Speech SDK, you are seeing this error ?

**Comment by FanChen2016** [comment]
> are seeing

Yes,  seeing this error when moved to the latest Speech SDK.

**Comment by FanChen2016** [comment]
> @jhakulin Yes, seeing this error when moved to the latest Speech SDK.

**Comment by FanChen2016** [comment]
> @FanChen2016 Thanks for the report, we will investigate. In 1.19.0 we have changed to xcframework. Are you using existing project with Speech SDK and when you moved to the latest Speech SDK, you are seeing this error ?

Yes, seeing this error when moved to the latest Speech SDK.

**Comment by gyuri-fluttech** [comment]
You can try out adding the following in your `Podfile`. I had a similar issue. 

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  $static_framework = ['NativeAudioPlugin']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
end
```

**Comment by jhakulin** [comment]
@FanChen2016 In the meantime we are investigating a proper fix, could you let me know if importing the Speech SDK in your swift app code where you use Speech SDK APIs would help to your issue ?

```
import MicrosoftCognitiveServicesSpeech
```

If this does not help, could you try to add use_modular_headers! in your Podfile and see if that helps.
```
target 'YourApp' do
    use_modular_headers!
end
```

**Comment by jhakulin** [comment]
@FanChen2016 We need to update the SpeechSDK Cocoapod to exclude the armv7, that should resolve this issue. 

As a workaround, you can exclude the armv7 from Any iOS Device by doing following
1. `pod install`, which will install MicrosoftCognitiveServicesSpeech-iOS (1.19.0)
2. Exclude armv7 architecture by adding line below into `MicrosoftCognitiveServicesSpeech-iOS.debug/release.xcconfig` files under your app project `Pods/Target Support Files/MicrosoftCognitiveServicesSpeech-iOS` directory and `Pods-<YourApp>.debug/release.xcconfig` files under `Pods/Target Support Files/Pods-<YourApp>` directory. When I tested this workaround with https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/from-microphone quickstart, I needed to update 4 xcconfig files in total. 
```
EXCLUDED_ARCHS[sdk=iphoneos*] = armv7
``` 
We will target to push new Cocoapod during this week.

**Comment by FanChen2016** [comment]
thanks.

**Comment by dargilco** [comment]
From the [1.20 release notes](https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
iOS: Compiling your Speech SDK application on any iOS Device when using CocoaPods is now fixed (GitHub issue 1320)

**Comment by jhakulin** [comment]
@gyuri-fluttech Unfortunately, there seems to be still a problem even with the fix made in 1.20.0. We made change in podspec to exclude armv7 and i386, but seems that does not work populate as excluded architectures atleast in all Xcode versions correctly. Based on the limited documentation what I can find, the correct fix for this would be to include armv7 flavor into xcframework package so that nothing needs to be excluded. We may consider that in future releases.

**Comment by gyuri-fluttech** [comment]
@jhakulin , thanks for the update. I can confirm that it is still there in 1.20.0 .

**Comment by garamon** [comment]
I add
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64 x86_64"
    end
  end
end
```
to the Podfile. I can successfully archive it.

* MicrosoftCognitiveServicesSpeech-iOS (1.20.0)
* Xcode 13.2.1
* OS: macOS 12.2.1
* Hardware ARM (M1)

**Comment by jhakulin** [comment]
@gyuri-fluttech Just for your information, we will add armv7 support in 1.21.0 release which should fix the issue also. ETA mid April.

**Comment by jhakulin** [comment]
Fix has been included in 1.21.0 Speech SDK for iOS, closing the item.

**Comment by dargilco** [comment]
Speech SDK 1.21 was release. See release notes: https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1210-april-2022-release
