### ISSUE TITLE
Text to speech timeouts with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED / USP error: timeout waiting for the first audio chunk

### ISSUE THREAD

**Issue by sibbl** [Azure-Samples/cognitive-services-speech-sdk#1692]
**Describe the bug**
Since 2022-10-12T17:38:57Z we found our working production speech to text component not working anymore.
We convert SSML via the Speech SDK to WAV audio and receive a "SynthesisStarted" event.
After like 30s we receive "SynthesizeCanceled" with "ServiceTimeout" and "USP error: timeout waiting for the first audio chunk".

**To Reproduce**
1. Start synthesizing SSML

**Expected behavior**
Audio data is received.

**Version of the Cognitive Services Speech SDK**
1.23, upgrade to 1.24 also didn't fix it

**Platform, Operating System, and Programming Language**
 - OS: Windows Server 2019 version 1809 (Azure VM) and Windows 11 22H2 version (local dev machines)
 - x64
 - C#

**Additional context**
Please find the Speech SDK log attached: [speech-sdk-synthesizer.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9779281/speech-sdk-synthesizer.log)

Some more noteworthy things:
* The same code on the same infrastructure has been running successfully for several weeks now and we never had this error before.
Our speech resource is on a S0 plan.
* We've already tried setting up another speech resource in another region, which also doesn't work.
* REST services via https://westeurope.tts.speech.microsoft.com/cognitiveservices/v1 work fine, which is our workaround for now.
* We can also successfully open a WebSocket connection to wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1
* Speech recognition on the same machine (with the same region + resource + subscription key) still work.

**Comment by ckl881003** [comment]
the same problem:USP error: timeout waiting for the first audio chunk

**Comment by trrwilson** [comment]
@yulin-li could you please advise?

From the log, it's clear that the connection is failing:
```
[208999]: 328ms SPX_TRACE_WARNING: synthesizer_connection.cpp:45 cannot get recognizer form connection of synthesizer.
...
[484114]: 348ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:98 CSpxUspTtsEngineAdapter::Speak: start to send synthesis request, request id : 3e1c06c0322746988c5f6fc8a0df2d9f, try: 0
...
[431144]: 396ms SPX_TRACE_SCOPE_EXIT:  uws_web_socket.cpp:149 WebSocketAdapter::UwsWebSocket::Open
[431144]: 396ms SPX_TRACE_ERROR:  usp_tts_engine_adapter.cpp:448 usp connection lost when trying to send message.
```

...But it's not clear to me if this is a topology issue or an active rejection.

Thank you!

**Comment by EgilSandfeld** [comment]
Experiencing the same issue here:

**USP error: timeout waiting for the first audio chunk**
**WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED**

This worked fine before updating Windows 10 to KB5018410, which afaik bumps up the TLS minimum from 1.0 to 1.2? Is this a clue?

```
[419445]: 81233ms SPX_TRACE_ERROR:  usp_tts_engine_adapter.cpp:232 USP error: timeout waiting for the first audio chunk
[419445]: 81233ms SPX_DBG_TRACE_FUNCTION:  synthesis_result.cpp:25 CSpxSynthesisResult::CSpxSynthesisResult
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxSynthesisResult' as '3874248'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BF1B6EE60; name='CancellationDetails_ReasonDetailedText'; value='USP error: timeout waiting for the first audio chunk'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BF1B6EE60; name='CancellationDetails_ReasonDetailedText'; value='USP error: timeout waiting for the first audio chunk'
[419445]: 81233ms SPX_DBG_TRACE_FUNCTION:  synthesis_result.cpp:30 CSpxSynthesisResult::~CSpxSynthesisResult
[419445]: 81233ms SPX_TRACE_ERROR:  usp_tts_engine_adapter.cpp:120 Synthesis cancelled without data received, retrying.
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BE7BAF3A8; name='RESULT-SynthesisBackend'; value='online (websocket)'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BE7BAF3A8; name='RESULT-SynthesisFirstByteLatencyMs'; value='-1'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BE7BAF3A8; name='RESULT-SynthesisFinishLatencyMs'; value='80085'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BE7BAF3A8; name='RESULT-SynthesisUnderrunTimeMs'; value='0'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0000028BE7BAF3A8; name='CancellationDetails_ReasonDetailedText'; value='USP error: timeout waiting for the first audio chunk'
[419445]: 81233ms SPX_DBG_TRACE_VERBOSE:  pull_audio_output_stream.cpp:162 Signal End of Writing is called
[657189]: 81233ms SPX_DBG_TRACE_SCOPE_ENTER:  synthesizer.cpp:1070 DispatchEvent task started...
[657189]: 81233ms SPX_DBG_TRACE_VERBOSE:  synthesizer.cpp:496 [0000028BF1BA9DE0]CSpxSynthesizer::CSpxSynthesizer::FireResultEvent
[657189]: 81233ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxSynthesisEventArgs' as '657912386'
[657189]: 81233ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:108 CSpxHandleTable::TrackHandle p=0x0000028BF18D9940
[657189]: 81233ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:118 CSpxHandleTable::TrackHandle class=ISpxSynthesisEventArgs, h=0x0000028BF18D9940, p=0x0000028BF18D9940, tot=1
[657189]: 81234ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:108 CSpxHandleTable::TrackHandle p=0x0000028BF1B6EE40
[657189]: 81234ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:118 CSpxHandleTable::TrackHandle class=ISpxSynthesisResult, h=0x0000028BF1B6EE40, p=0x0000028BF1B6EE40, tot=2
[657189]: 81234ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:108 CSpxHandleTable::TrackHandle p=0x0000028BF1B6EE60
[657189]: 81234ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:118 CSpxHandleTable::TrackHandle class=ISpxNamedProperties, h=0x0000028BF1B6EE60, p=0x0000028BF1B6EE60, tot=4
[495759]: 101321ms SPX_TRACE_SCOPE_ENTER:  uws_web_socket.cpp:247 WebSocketAdapter::UwsWebSocket::OnWebSocketOpened
[495759]: 101322ms SPX_TRACE_ERROR:  web_socket.cpp:944 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=2[0x00000002], time=2022-10-14T09:43:54.0277453Z
[495759]: 101322ms SPX_TRACE_INFO:  usp_connection.cpp:908 TS:60103, TransportError: connection:0xe7b179d0, code=5, string=Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1
X-ConnectionId: 2d36782173e246909935cfc3442f3c0f
[495759]: 101322ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:799 Response: On Error: Code:5, Message: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1
X-ConnectionId: 2d36782173e246909935cfc3442f3c0f.```

**Comment by sibbl** [comment]
> This worked fine before updating Windows 10 to KB5018410, which afaik bumps up the TLS minimum from 1.0 to 1.2? Is this a clue?

We also feel like it could be related to the machines it runs on. We have a dev deployment of the exactly the same binaries from the same CI pipeline and configs deployed to a Windows Azure App Service instead of the Windows Server Azure VM. There, it's still working.

However, as far as our app insights logs tell us, the Azure VM wasn't updated between the point where it still was working and the point when it was first broken. So this speaks against the theory.

**Comment by bobandrew** [comment]
I'm having same error. My solution has been working good a several days and yesterday I stumbled onto the same error 'USP error: timeout waiting for the first audio chunk'. If will be usefull I attach my logs below. Be glad any help.
Here is log:
[207990]: 40303ms SPX_TRACE_VERBOSE interop_factory.cs:83 Dispose(True) called for 057d59b0
[207990]: 40303ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:175 CSpxHandleTable::StopTracking(h) h=0x057D59B0
[207990]: 40303ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:190 CSpxHandleTable::StopTracking(h) class=ISpxNamedProperties, h=0x057D59B0, p=0x057D59B0, tot=3
[207990]: 40303ms SPX_TRACE_VERBOSE interop_factory.cs:83 Dispose(True) called for 057d59a0
[207990]: 40303ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:175 CSpxHandleTable::StopTracking(h) h=0x057D59A0
[207990]: 40303ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:190 CSpxHandleTable::StopTracking(h) class=ISpxSynthesisResult, h=0x057D59A0, p=0x057D59A0, tot=1
[207990]: 40303ms SPX_DBG_TRACE_SCOPE_EXIT:  synthesizer.cpp:1070 DispatchEvent task complete!
[699469]: 40304ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:468 ISpxNamedProperties::GetStringValue: this=0x057D59B0; name='CancellationDetails_ReasonDetailedText'; value='USP error: timeout waiting for the first audio chunk'

**Comment by francescoStrada** [comment]
I am facing exctley the same problem, 

> Windows 10 to KB5018410, which afaik bumps up the TLS minimum from 1.0 to 1.2?

Same for us, the PCs having installed Windows 10 to KB5018410 stopped working. Is it possible to manually force TLS to 1.0??

**Comment by sibbl** [comment]
I just took another look at the system events directly on our VM and can confirm that the update KB5018419 was installed at Oct 12th there, also including the [TLS changes](https://support.microsoft.com/en-us/topic/kb5017811-manage-transport-layer-security-tls-1-0-and-1-1-after-default-behavior-change-on-september-20-2022-e95b1b47-9c7c-4d64-9baf-610604a64c3e). I missed this in our logs outside the VM before.

**Comment by daimig** [comment]
> I am facing exctley the same problem,
> 
> > Windows 10 to KB5018410, which afaik bumps up the TLS minimum from 1.0 to 1.2?
> 
> Same for us, the PCs having installed Windows 10 to KB5018410 stopped working. Is it possible to manually force TLS to 1.0??


this may help the problem https://www.youtube.com/watch?v=d-UBWHT_eUg

**Comment by yulin-li** [comment]
Hi, we acknowledged this issue that the TTS service in unavailable from Speech SDK on Windows platform after installing the updates (KB5018427 for Windows 11 22H2, and KB5018418 for 21H2). We are investigating this issue.

The TTS service supports both TLS v1.2 and v1.3, which could be verified using https://www.ssllabs.com/ssltest/analyze.html?d=westus2.tts.speech.microsoft.com

**Comment by Sezar** [comment]
20% chance it works, 80% error, what's the source of the error?

**Comment by rhurey** [comment]
The Windows fix has been released, information can be found here: https://learn.microsoft.com/windows/release-health/resolved-issues-windows-server-2022#2924msgdesc

**Comment by rhurey** [comment]
A full set of the release links for various operating systems.

This update will not immediately be made available through Windows Update, but will be in the next rollup that is.

[Windows 11 22H2	KB 5019509 ](https://support.microsoft.com/topic/october-18-2022-kb5019509-os-build-22621-675-out-of-band-4fdf3458-148a-46bd-b163-ecb93c282726)
[Windows SV 21H2	KB 5020387 ](https://support.microsoft.com/topic/october-17-2022-kb5020387-os-build-22000-1100-out-of-band-5e723873-2769-4e3d-8882-5cb044455a92)
[Windows Server 2022	KB 5020436](https://support.microsoft.com/topic/october-17-2022-kb5020436-os-build-20348-1131-out-of-band-18baa25a-5fc0-4118-9b89-ddbe9819e578)
[2004 \ 20H1, 20H2, 21H1, 21H2	KB 5020435 ](https://support.microsoft.com/topic/october-17-2022-kb5020435-os-builds-19042-2132-19043-2132-and-19044-2132-out-of-band-243f34de-2f44-4015-a224-1b68a4132ca5)
1909 \ 19H2	KB 5020437
[1809 \ RS5 \ Windows Server 2019	KB 5020438](https://support.microsoft.com/topic/october-17-2022-kb5020438-os-build-17763-3534-out-of-band-cd499c1a-6d60-49a1-9a40-fad42c1d393a)
1607 \ RS1 \ Windows Server 2016	KB 5020507
Windows 10 RTM	KB 5020440
[Windows Server 2012 R2	KB 5020447 ](https://support.microsoft.com/topic/kb5020447-out-of-band-update-for-windows-8-1-and-server-2012-r2-october-17-2022-faba9068-c17b-4a84-ae8b-4339b4a46a2e)
[Windows Server 2012	KB 5020449](https://support.microsoft.com/topic/kb5020449-out-of-band-update-for-windows-server-2012-october-17-2022-6910b46a-261c-499e-8e6c-45d7daa053d7)
[Windows Server 2008 R2	KB 5020448 ](https://support.microsoft.com/topic/kb5020448-out-of-band-update-for-windows-7-sp1-and-server-2008-r2-sp1-october-17-2022-38841bc3-cfd3-467e-9a61-809e5ae7b91f)

**Comment by ckl881003** [comment]
> 

I tried installing _**Windows 11 22H2 KB 5019509**_  on Windows 11 22H2 which didn't fix the issue, but installing KB5020435 on Windows 10 22H2 fixed the issue.

**Comment by sibbl** [comment]
I can confirm that it's working again with the updates. Thanks for the quick investigation and quick fix! 👍

If there's one thing I'd like to suggest, then it's a communication of the issue's progress at a single place.

I've posted [a question at MS Learn](https://learn.microsoft.com/en-us/answers/questions/1046264/speech-to-text-failed-with-error-ws-open-error-und.html) 6 days ago, where I was told to post this Github issue. Which makes sense 100% to me as issues from this and other repos can be linked.

However, there was then created [another post at MS Learn](https://learn.microsoft.com/en-us/answers/questions/1047034/text-to-speech-usp-error-timeout-waiting-for-the-f-1.html) 5 days ago where some helpful progress updates were posted, which were not available to us here after subscribing to the Github post.

I personally still don't know where I'd post the next issue first...
a) to give you direct and helpful feedback
b) to allow others to find and subscribe to updates of the issue
c) for me to get all the updates related to the issue.

I'd appreciate it, if this can be communicated more clearly in the future to make the life easier for us but also for you. Thanks a lot again!

**Comment by rhurey** [comment]
Looking into the 22H2 patch with the Windows team….

**Comment by TonyHenrique** [comment]
Is there a patch for Windows 11 - 21H2 - version 10.0.22000.1098 ?

I am getting an error while trying to use Microsoft.CognitiveServices.Speech (version 1.24.0) Text-to-Speech NuGet package with `hr-HR-GabrijelaNeural` and `hr-HR-SreckoNeural` 
`CANCELED: Reason=Error CANCELED: ErrorCode=ServiceTimeout CANCELED: ErrorDetails=[USP error: timeout waiting for the first audio chunk]`

I also tried to use:
`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

**Comment by alexanikiev** [comment]
For clarity: On Windows 11 TTS works from time to time very occasionally (it worked for me once this morning) and significantly slower, but almost always still throws the timeout error even with the referenced KB installed. Appreciate your help @rhurey to solve this issue for us!

**Comment by rhurey** [comment]
There are some non-deterministic factors that could allow the connection to work occasionally in 22H2.

@TonyHenrique [2004 \ 20H1, 20H2, 21H1, 21H2 KB 5020435] (https://support.microsoft.com/topic/october-17-2022-kb5020435-os-builds-19042-2132-19043-2132-and-19044-2132-out-of-band-243f34de-2f44-4015-a224-1b68a4132ca5) should cover 21H2

**Comment by TonyHenrique** [comment]
@rhurey  I tried, but all those are for Windows 10, could not find one that installs on Microsoft Windows [versão 10.0.22000.1098]

https://www.catalog.update.microsoft.com/Search.aspx?q=KB5020435
![image](https://user-images.githubusercontent.com/6307623/196802441-2d2bb818-d3c5-4b56-8ca1-8c29d6c207db.png)

Can you tell me a link for Microsoft Windows [versão 10.0.22000.1098]  x64  ?

**Comment by rhurey** [comment]
Whoops... Sorry, decoding Windows Servicing builds...

https://support.microsoft.com/topic/october-17-2022-kb5020387-os-build-22000-1100-out-of-band-5e723873-2769-4e3d-8882-5cb044455a92 That should bump to 10.22000.1100

**Comment by TonyHenrique** [comment]
@rhurey I downloaded 2022-10 Atualização Cumulativa do Windows 11 para sistemas operacionais baseados em x64 (KB5020387) 
but still not able to install.
This update is not applicable to your computer

**Comment by TonyHenrique** [comment]
Thank you, @rhurey ! 
I Installed KB5020387 ; now Microsoft Windows shows version 10.0.22000.1100 and Microsoft.CognitiveServices.Speech is working!

**Comment by rhurey** [comment]
The only mitigation for 22H2 is to uninstall KB5018427. We don't yet have a published fix for that version.

**Comment by eppstephan** [comment]
How to uninstall KB5018427 when it is not listed under the updates that can be uninstalled?

**Comment by rhurey** [comment]
You'd need to uninstall KB5019509 first. The rollups are cumulative.

**Comment by eppstephan** [comment]
I cannot uninstall all required updates until 22H2. After uninstalling KB 5017321, KB 5017321 is again the only update I can uninstall and the subsequent updates which should be uninstalled, too, are not listed under the updates to be uninstalled.

![image](https://user-images.githubusercontent.com/113251093/197035573-ca7fb1d1-9978-4013-973e-6da22b8ccff1.png)
![image](https://user-images.githubusercontent.com/113251093/197035240-e5e18813-22f1-4654-bc43-eab4b729a1ba.png)

**Comment by rhurey** [comment]
An update: For OS's before Win11 22H2 there should now be an optional _2022-10 Cumulative Update Preview_ that you can get from Windows update by clicking "Check for updates" that has the fix.
 
For 22H2 a manually installable KB5018496 was published: [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5018496)
 
These should all rollup into November's automatic update cycle.

**Comment by SeriousOldMan** [comment]
Hmm, after the preview update it worked once, but now the same problem again. What is surprising, is, that the connection against the voice recognition service works without a problem, the connection issue is only related to the voice synthetization.
