### ISSUE TITLE
Speech with Entra: Azure Speech Endpoint: Unable to contact server. StatusCode: 1006

### ISSUE THREAD

**Issue by NicoPlattner** [Azure-Samples/cognitive-services-speech-sdk#2692]
**Describe the bug**

I am getting the following error trying to use the Speech SDK with Entra authentication.
Error: Unable to contact server. StatusCode: 1006, wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1 Reason: undefined

I am using a Cognitive Services Multi account ressource and when I query the translation endpoint everything works fine with my auth token, however it doesn't when trying to use the speech endpoint with the speech sdk.

**To Reproduce**

Here's my minimal version using next.js

dependencies

``` JSON
    "next": "^14.2.15",
    "react": "^18",
    "react-dom": "^18.3.1",
    "@azure/identity": "^4.4.0",
    "@azure/msal-browser": "^3.26.1",
    "@azure/msal-react": "^2.1.1",
    "microsoft-cognitiveservices-speech-sdk": "^1.40.0"
```

layout.js

``` Javascript
'use client'

import { PublicClientApplication } from "@azure/msal-browser";
import { MsalProvider, MsalAuthenticationTemplate, useMsal } from "@azure/msal-react";
import { InteractionType } from "@azure/msal-browser";

export default function RootLayout({ children }) {

  const msalConfig = {
    auth: {
      clientId: "APPLICATION ID",
      authority: "https://login.microsoftonline.com/<TENANT ID>",
      redirectUri: 'http://localhost:3000',
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
    },
  };
  
  const msalInstance = new PublicClientApplication(msalConfig);

  return (
    <html lang="en">
      <body>
        <MsalProvider instance={msalInstance}>
          <MsalAuthenticationTemplate interactionType={InteractionType.Redirect}>
            {children}
          </MsalAuthenticationTemplate>
        </MsalProvider>
      </body>
    </html>
  );
}

```

page.js

``` Javascript
'use client'

import { useMsal } from "@azure/msal-react"
import * as sdk from "microsoft-cognitiveservices-speech-sdk"
import { useEffect, useState } from "react"


export default function Home() {
  const { instance } = useMsal()
  const [error, setError] = useState(null)

  const region = "westeurope"
  const resourceId = "<RESOURCE ID>"

  const tokenRequest = {
      scopes: ["https://cognitiveservices.azure.com/.default"]
  };

  const fetchToken = async () => {
    try {
        const account = instance.getAllAccounts()[0];

        const response = await instance.acquireTokenSilent({
            ...tokenRequest,
            account,
        })
        return response.accessToken
    } catch (error) {
        if (error) {
            const response = await instance.acquireTokenPopup(tokenRequest)
            return response.accessToken
        }
        throw error
    }
  };

  useEffect(() => {
    fetchToken().then(token => 
    {
      const authToken = "aad#" + resourceId + "#" + token
      const speechConfig = sdk.SpeechConfig.fromAuthorizationToken(authToken, region)

      const synthesizer = new sdk.SpeechSynthesizer(
        speechConfig
      )

      synthesizer.speakTextAsync(
        "Hello, world!",
        function (result) {
          if (result.reason === sdk.ResultReason.SynthesizingAudioCompleted) {
            console.log("synthesis finished.")
          } else {
            setError(result.errorDetails)
            console.error("Speech synthesis canceled, " + result.errorDetails)
          }})
      synthesizer.close();
    })
  }, [instance])


  return (
    <div>
      Error: {error}
    </div>
  );
}

```

**Expected behavior**

speakTextAsync shouldn't throw an error

**Version of the Cognitive Services Speech SDK**

1.41.0

**Platform, Operating System, and Programming Language**

Platform: Next.js, Browser
Operating System: Windows 11
Programming Language: Javascript

**Additional context**
Error occuring in: WebsocketMessageAdapter.js

```
WebSocket connection to 'wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1?Authorization=Bearer%20aad%23<RESSOURCEID>%23<TOKEN>&X-ConnectionId=<SOMEID>' failed: 
open @ WebsocketMessageAdapter.js:73
open @ WebsocketConnection.js:68
eval @ SynthesisAdapterBase.js:295

```
Error occuring in: page.js
```
Speech synthesis canceled, Unable to contact server. StatusCode: 1006,
                    wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1 Reason:  undefined

```
would be super grateful for any help!

**Comment by 9hsein5** [comment]
I am getting same error, any update?

**Comment by NicoPlattner** [comment]
For us the issue was resolved last friday (February 14th 2025) when the Azure Team released a fix that now allows longer tokens to be used with the TTS, S2S, STT endpoints of Cognitive Services.
Sometimes it can take a while for a change to propagate to all regions, so perhaps try again in a few days? I know our specific issue was resolved in the West Europe region, so you could also try that region and see if it helps.

Our specific issue:
Our problem was that the access token we received from/for Cognitive Services was very large (> 8 KB) since in our corporate environment our users are in a large amount of groups and the token included all these group ids.
Now the problem was that (in JS) that token was passed in the request URL and something (the WAF protecting the endpoints ???) blocked these long request URLs.
This was specific to the JS version of the Speech SDK, since the Browser/JS - Websocket API doesn't allow passing Auth Tokens as Headers, and it instead passed them as URL params. All other implementations of the Speech SDK pass the token as a header which is/was fine anyway.

The fix that Microsoft implemented and that helped us was to allow request URLs of up to 16 KB.

**Comment by 9hsein5** [comment]
I'm running it in Canada Central and still experiencing the same issue. Could you share your configuration details? Here's the current setup I'm using:

```
"use server";
import { DefaultAzureCredential, getBearerTokenProvider } from "@azure/identity";

export const GetSpeechToken = async () => {
  if (
    process.env.AZURE_SPEECH_REGION === undefined ||
    process.env.AZURE_SPEECH_RESOURCE_ID === undefined
  ) {
    return {
      error: true,
      errorMessage: "Missing Azure Speech credentials",
      token: "",
      region: "",
    };
  }

  if (!process.env.AZURE_SPEECH_KEY) {
    const credential = new DefaultAzureCredential();
    const token = await credential.getToken("https://cognitiveservices.azure.com/.default");

    return {
      error: false,
      errorMessage: "",
      token: `aad#${process.env.AZURE_SPEECH_RESOURCE_ID}#${token.token}`,
      region: process.env.AZURE_SPEECH_REGION
    };
  }

  const response = await fetch(
    `https://${process.env.AZURE_SPEECH_REGION}.api.cognitive.microsoft.com/sts/v1.0/issueToken`,
    {
      method: "POST",
      headers: {
        "Ocp-Apim-Subscription-Key": process.env.AZURE_SPEECH_KEY!,
      },
      cache: "no-store",
    }
  );

  return {
    error: response.status !== 200,
    errorMessage: response.statusText,
    token: await response.text(),
    region: process.env.AZURE_SPEECH_REGION,
  };
};

```

**Comment by NicoPlattner** [comment]
It's quite similar, though we are using msal for acquring the access token

```
export const getToken = async (msalInstance) => {
    try {
        const account = msalInstance.getActiveAccount();
        const response = await msalInstance.acquireTokenSilent({
            scopes: ["https://cognitiveservices.azure.com/.default"],
            account: account,
        });
        return response.accessToken;
    } catch (error) {
        console.error("Failed to fetch token:", error);

        throw error;
    }
};
```
One thing that also took me a while to figure out was that the Speech Config needs to be created differently for a ressource protected by a private endpoint. Perhaps that helps.

For TTS:
```
        this.speechConfig = sdk.SpeechConfig.fromEndpoint(
            new URL("wss://" + endpoint + "/tts/cognitiveservices/websocket/v1")
        );
     
        this.speechConfig.authorizationToken = this.authorizationToken;

```
For STT:
```
        this.speechConfig = sdk.SpeechTranslationConfig.fromEndpoint(
            new URL("wss://" + endpoint + "/s2s/speech/translation/cognitiveservices/v1")
        );

        this.speechConfig.authorizationToken = this.authorizationToken;
```

**Comment by 9hsein5** [comment]
That's quite interesting—it's very similar to what I'm experiencing. Are you not including the `aad#${process.env.AZURE_SPEECH_RESOURCE_ID}#${token.token}` portion? I found it confusing because it works locally when I use the `"Ocp-Apim-Subscription-Key" from process.env.AZURE_SPEECH_KEY!`, but it fails during the build. And when I switch to using aad#${process.env.AZURE_SPEECH_RESOURCE_ID}#${token.token}, I encounter a similar error as you. I set it up based on the documentation provided in this [link](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-text-to-speech?tabs=streaming#use-microsoft-entra-authentication).

**Comment by NicoPlattner** [comment]
I don't have access to my PC rn, so take this with some caution

Yes we also use the aad#<ressourceId>#<token>
We pretty much use the same code I posted originally, only the way we create the configs changed
You mentioned that it works with the subscription key, does the way you create the config change?
There's smith like speechconfig.fromSubscriptionkey and there's a fromendpoint that's you'd use with the entra token AND a private endpoint 
If there's no PE you should use fromAuthorizationtoken 

The behavior you're describing would also be typical if you have the same issue we had with the long token length, since the subscription key is short and won't cause issues, but a long access token did cause issues

**Comment by 9hsein5** [comment]
I'm using fromAuthorizationToken, but I suspect it's the same issue due to the long access token. My resource name is also lengthy, so the access token ends up being a bit longer, as you mentioned.

**Comment by GalDayan** [comment]
Same here..

**Comment by ForrestGumb** [comment]
@NicoPlattner Please use custom domain when you use Entra authentication.
Azure doc: 
https://learn.microsoft.com/azure/ai-services/speech-service/how-to-configure-azure-ad-auth?tabs=portal&pivots=programming-language-csharp

From the error information below, seem you're not sending request to your custom domain.
WebSocket connection to 'wss://westeurope.tts.speech.microsoft.com/cognitiveservices/websocket/v1?Authorization=Bearer%20aad%23<RESSOURCEID>%23<TOKEN>&X-ConnectionId=<SOMEID>' failed:
