### ISSUE TITLE
Getting Error while uploading text data for Custom Training 

### ISSUE THREAD

**Issue by manojmsrit** [Azure-Samples/cognitive-services-speech-sdk#603]
I am trying to upload text data for Custom Training ( Language model ) for speech to Text .  But I am getting "Failed to upload data DE-LM. Error: A form field with content type text/plain and content disposition name languagedata is missing. Try again in a few moments" error message every time. Please suggest me. 

![Error Message](https://user-images.githubusercontent.com/49993125/80230395-2e45fb80-8652-11ea-81b7-06215f07d453.png)

Thanks,
Manoj

**Comment by oscholz** [comment]
@ArcherAZ Could you please have a look at this and suggest a path forward?

**Comment by manojmsrit** [comment]
Any updates on this issue ?

**Comment by ArcherAZ** [comment]
Hey @manojmsrit , thanks for reporting this. The issue should be well fixed now. Please have a re-try, and let us know your subscription region if there is still question. (Best to create an [Azure support ticket](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/support) in the future so that our service support team can capture your asks timely)

**Comment by megharangaswamy** [comment]
Hi @ArcherAZ ,

Even I am trying to upload related-text data to train language model, but I am getting the same error. Kindly help.

![MS-azure-error](https://user-images.githubusercontent.com/26714845/80471587-e53cc280-8943-11ea-8066-8b31ad142d30.png)



Thanks,
Megha

**Comment by manojmsrit** [comment]
Hello @ArcherAZ : I still face the same issue . My subscription region is "West Europe". I have chosen German Language selection for training. Thank you

**Comment by RichardSunMS** [comment]
@manojmsrit , thanks for reporting this and sorry for the inconvenience.
We are unable to repro this issue with a West Europe speech resource, can you try to Ctrl + F5 to force refresh the client script/js, and try again?

**Comment by manojmsrit** [comment]
@RichardSunMS @ArcherAZ  : I tried as per your suggestions..........But still I am getting same error...And I am unable to create in (Azure support ticket ) because of account credibility.

**Comment by luqman-hussain** [comment]
@manojmsrit I had this same issue. Its most likely because you're txt file is utf-8 instead of utf-8-bom encoded. please check using notepad++

The portal could be a lot better!
![image](https://user-images.githubusercontent.com/58002763/81175102-dcc73600-8f9a-11ea-8b13-202c4dd4808b.png)

**Comment by manojmsrit** [comment]
@luqman-hussain : Thank you for the suggestion. It worked for me.
